### ISSUE TITLE
Use UP/DOWN arrow keys

### ISSUE THREAD

**Issue by robin-a-meade** [sustmi/gnome-shell-extension-historymanager-prefix-search#1]
Would it be possible to make this work with the UP/DOWN arrow keys instead of PageUp/PageDown?

It's common to use the UP/DOWN arrow keys in the terminal for history-search by putting the following in `.bashrc`:

```sh
bind '"\e[A"':history-search-backward
bind '"\e[B"':history-search-forward
```

I would be great to use the same combination for **Alt+F2**, especially since many laptop keyboards require using a Fn key for PageUp/PageDown.

**Comment by sustmi** [comment]
I personally do not like to use cursor keys for history search because then I am unable to move one command back or forward in history when the cursor is in the middle of a command (it would do history search instead).
However, I have numpad with dedicated PageUp/PageDown keys and I also get that people have different preferences. I will try to make the extension configurable so that you can choose any keys you want. But if it would be to hard (I do not know whether there is any reusable "Choose key" UI component) I will just create simple radio/check option with two choices:
- PageUp/PageDown
- Up/Down arrow keys

Please be patient. Hopefully I will find time for this soon.

**Comment by sustmi** [comment]
The new version `v12` (pending revision on extensions.gnome.org) supports switching between PageUp+PageDown and Up+Down.

**Comment by robin-a-meade** [comment]
Thanks. Works great!
